### ISSUE TITLE
[potential bug] Extremely different execution averages between ingame and ui

### ISSUE THREAD

**Issue by LordTylus** [sirhamsteralot/HaE-PBLimiter#11]
Hello there,

today I had some reports of our players that their Programmable blocks overheat pretty fast.

I was unable to find the source for it and run the following test script for measurments
```
public Program() {
    Runtime.UpdateFrequency = UpdateFrequency.Update1;
}

double avg;

public void Main(String argument, UpdateType updateSource) {

    avg = avg*0.995+Runtime.LastRunTimeMs*0.005;

    Echo(avg+"");
}
```

The game Displayed 0.005184 ms

However in the Server UI The average shown was 0.1584 ms and therefore signifikantally higher. It even peaks at 0.25 at times. For a simple one liner this is too high. 

I also tested it on my local Torch Server where it displayed 0.07 ms still a bit high, but much better compared to the other one. 

Also the problems seem to appear just recently.

**Comment by sirhamsteralot** [comment]
should be fixed in v1.0.9.4
