### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by AnonymousMonkey75** [sirhamsteralot/HaE-PBLimiter#12]
These exceptions keep occurring when running the plugin. I don't know why. I'm not active in the GUI when these occur. 

https://pastebin.com/dkd3Bd7k

**Comment by sirhamsteralot** [comment]
how often does it occur?

**Comment by sirhamsteralot** [comment]
this should be fixed in the latest update, let me know if it isnt as this is very hard to reproduce
