### ISSUE TITLE
[Safe Zone Issue] Plugin can't break PB in Safe Zones

### ISSUE THREAD

**Issue by ghost** [sirhamsteralot/HaE-PBLimiter#13]
Hello, 

It seems that when a Programmable Block is in a safe zone (player or admin) the PB Limiter plugin can't break the Block. Since it is in a safe zone it might be why.

I hope you can fix this, your plugin is the one thing we all need :)

Good day to you.

**Comment by sirhamsteralot** [comment]
was actually fixed in the latest update by requiring PB's be recompiled when they burn out, just forgot to close the issue.
