### ISSUE TITLE
After the program block is detonated by the warhead the server crashes

### ISSUE THREAD

**Issue by homemonster** [sirhamsteralot/HaE-PBLimiter#14]
After the program block is detonated by the warhead the server crashes.
This fact was revealed when using the DOM Deffense script.

Then a test was carried out on the explosion of the warhead near the stationary working PB - the server crashed, but not immediately, for some time it worked.

At the same time the data from the plugin table about the running program block froze.
As a result if bad players learn about the current problem they can safely lay down the server.

**Comment by homemonster** [comment]
00:16:02.1095 [FATAL]  Initializer: System.InvalidOperationException: An ItemsControl is inconsistent with its items source.
  See the inner exception for more information. ---> System.Exception: Information for developers (use Text Visualizer to read this):
This exception was thrown because the generator for control 'System.Windows.Controls.DataGrid Items.Count:3' with name 'DataGrid1' has received sequence of CollectionChanged events that do not agree with the current state of the Items collection.  The following differences were detected:
  Accumulated count 2 is different from actual count 3.  [Accumulated count is (Count at last Reset + #Adds - #Removes since last Reset).]

One or more of the following sources may have raised the wrong events:
     System.Windows.Controls.ItemContainerGenerator
      System.Windows.Controls.ItemCollection
       MS.Internal.Data.EnumerableCollectionView
        System.Collections.Generic.Dictionary`2+ValueCollection[[System.Int64, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[HaE_PBLimiter.PBTracker, HaE_PBLimiter, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]
(The starred sources are considered more likely to be the cause of the problem.)

The most common causes are (a) changing the collection or its Count without raising a corresponding event, and (b) raising an event with an incorrect index or item parameter.

The exception's stack trace describes how the inconsistencies were detected, not how they occurred.  To get a more timely exception, set the attached property 'PresentationTraceSources.TraceLevel' on the generator to value 'High' and rerun the scenario.  One way to do this is to run a command similar to the following:
   System.Diagnostics.PresentationTraceSources.SetTraceLevel(myItemsControl.ItemContainerGenerator, System.Diagnostics.PresentationTraceLevel.High)
from the Immediate window.  This causes the detection logic to run after every CollectionChanged event, so it will slow down the application.

**Comment by sirhamsteralot** [comment]
Attempted fix in v1.0.10.6, reopen if this crash still occurs.
