### ISSUE TITLE
"!pblimiter status" displays some blocks twice

### ISSUE THREAD

**Issue by azazar** [sirhamsteralot/HaE-PBLimiter#21]
Status command displays some blocks twice. Does it count twice against per player's limit too?

![pblimiter bug2](https://user-images.githubusercontent.com/2816075/78424245-ce70bc00-7674-11ea-9e6b-df89b05ee41c.png)

**Comment by azazar** [comment]
I think, that it occurs when ALE ShipFixer's plugin "!fixship" command issued

**Comment by LordTylus** [comment]
I dont see how deleting an adding a new grid would cause that
unless of course PB Limiter does not react accordingly to PBs gone missing.

However thats probably not a huge issue, as he has code in place to filter out nonexistent, and non functional PBs as well as grids which havent been updated for quite a while on execution.

So its most likely just a display issue and if its affecting PB exeucton it will only do for a shite while

**Comment by sirhamsteralot** [comment]
what Tylus said, they will count but since they wont be updated they will time out and not counted after a specified time you can set in the limiter settings.
