### ISSUE TITLE
[Feature request] allow scripts to perform cleanup before damaging pbs

### ISSUE THREAD

**Issue by azazar** [sirhamsteralot/HaE-PBLimiter#22]
Damaging PBs often cause vessels crashing when PBs that control gyros or thrusters get disabled during flight. If there was a method to allow ingame script perform cleanup before damaging PB that could save player a lot of time. Invoking Program.Save or Program.Main with certain argument could allow ingame script to perform cleanup.

**Comment by azazar** [comment]
There is a pull request with that feature: https://github.com/sirhamsteralot/HaE-PBLimiter/pull/26 .

**Comment by sirhamsteralot** [comment]
Released
