### ISSUE TITLE
[Feature request] Add Admin command to see PBs of other player or Faction

### ISSUE THREAD

**Issue by LordTylus** [sirhamsteralot/HaE-PBLimiter#25]
Hello there,

I would like a command to have easy access to the PB Limiter metrics as admin either via discord bridge plugin or ingame.

I wont always want to connect to my Root Server, navigate the Torch UI to do check PBs out.

So a command for ingame display would be very much appreciated.

**Comment by sirhamsteralot** [comment]
something like !statistics \<playername\>?

**Comment by LordTylus** [comment]
Well !statistics is pretty generic

but something along those lines

I mean a !pblimiter statistics could output all PBs ordered descending by runtime
!pblimiter statistics player &lt;Playername> filters for player
!pblimiter statistics faction &lt;FactionTag> filters for faction

And in all caseses the response should show a grand total at the end.

When I am online I expect a dialog to open as its easier to read. 
When console executes someting (so player == null) I would expect to get a context respond in chat. But not for every PB (as it tends to crash discord)

Similar to how I do it in my plugins I just write everything to a StringBuilder and either send it as dialog or context respond.

**Comment by sirhamsteralot** [comment]
I will look into this soon

**Comment by sirhamsteralot** [comment]
Implemented in 2024-1 release branch, example usage: !pblimiter investigate <playername>
