### ISSUE TITLE
[Bug] PBLimiter doesn't count average execution time as expected

### ISSUE THREAD

**Issue by azazar** [sirhamsteralot/HaE-PBLimiter#27]
I've made three scripts that do same amount of work and PBLimiter's counter values varies greatly for each of them. PBLimiter counts extra average time for any PBs that do not execute every game frame, blowing up PBs that generate less stress. That's may be good for microlag prevention, but it also encourage script writers to use Update1 frequency where Update10 or Update100 frequencies should be used, causing extra server load.

#### Scripts

```cs
// Update1

public Program()
{
    Runtime.UpdateFrequency = UpdateFrequency.Update1;
}

public void Main(string argument, UpdateType updateSource)
{
    Me.CustomData="TEST";
}
```

```cs
// Update10

public Program()
{
    Runtime.UpdateFrequency = UpdateFrequency.Update10;
}

public void Main(string argument, UpdateType updateSource)
{
    for(int i = 0; i < 10; i++) {
        Me.CustomData="TEST"+i;
    }
}
```

```cs
// Update1 working every 10th tick

public Program()
{
    Runtime.UpdateFrequency = UpdateFrequency.Update1;
}

int Tick = 0;

public void Main(string argument, UpdateType updateSource)
{
    Tick++;
    if (Tick % 10 != 0) {
        return;
    }
    for(int i = 0; i < 10; i++) {
        Me.CustomData="TEST"+i;
    }
}
```

#### Averages

![pblimiter bug3](https://user-images.githubusercontent.com/2816075/78536123-fc313e80-77f5-11ea-8197-4aa4e02af97f.png)

**Comment by azazar** [comment]
And a minute after server start and previous screenshot.

![pblimiter bug3 +1m](https://user-images.githubusercontent.com/2816075/78536416-7bbf0d80-77f6-11ea-86f2-81288ddab770.png)

**Comment by sirhamsteralot** [comment]
Released
