### ISSUE TITLE
v1.1.0.0 doesn't seem to overheat pb's

### ISSUE THREAD

**Issue by kontu** [sirhamsteralot/HaE-PBLimiter#29]
v1.1.0.0 doesn't seem to overheat pb's

Running Torch v1.3.1.114-master, HaE-PBLimiter v1.1.0.0:
We're seeing these PB's all over 1MS for the last 10 minutes now not being shut off (value of MS is updating normally in the display): https://i.imgur.com/zaycKW4.png
Using these settings : https://i.imgur.com/1Gb3P1S.png

We've used these settings for a long time without issue, and it's been working fine till today's update. There are no player exceptions; and we are seeing the same issue with PB's not overheating/being killed off on at least two other torch instances of ours

**Comment by sirhamsteralot** [comment]
I dont seem to be able to reproduce this issue locally, would you mind sharing the logs here?

**Comment by kontu** [comment]
Full screenshot captured at time of log capture - those blocks have been reporting those high numbers for the entire ~2hr uptime 
https://i.imgur.com/mnQZrVF.png
Keen and Torch Logs captured right after that image : https://mega.nz/file/0RoTUSwB#ZriajH9kraDWJatTWApf980CylROr8qQs7K2o2PG91M
I did edit the torch logs, but only to remove "Chat:" lines so we didn't accidentally reveal player in-game info.
I am happy to provide / collect any data within my power you can think of

**Comment by sirhamsteralot** [comment]
haha i see the issue, look at the E sign after the larger numbers 6.55E-38 is actually really tiny (E-38 = *10^-38) not a bug ;)

**Comment by kontu** [comment]
Alright that's fair :) Can I request that "average MS" gets normalized / rounded to say, 4-5 places instead of looping out forever like that? (I'm happy to open it as a new "issue" feature request if you'd like).
Having it display the way it is is very confusing

**Comment by sirhamsteralot** [comment]
at that point they would just display as 0.0000, i think i would prefer to keep it like this as its more accurate albeit a little less readable.

**Comment by rexxar-tc** [comment]
Showing 0 is literally fine. Nobody needs to know their PB is taking 0.483 ns. If you're really worried, just output "< 0.0000001ms" or something. E notation *isn't* readable for normal users, especially not after fifteen decimal places

**Comment by sirhamsteralot** [comment]
Implemented.

**Comment by kontu** [comment]
I did notice today I had one PB showing in notation again
https://i.imgur.com/Uj8tQ9h.png

Most of all the rest look great, this is the first time i've seen it report in notation since you implemented the change
