### ISSUE TITLE
Player names not resolving to Steam IDs

### ISSUE THREAD

**Issue by klemens-st** [sirhamsteralot/HaE-PBLimiter#32]
I tried configuring player exceptions like this:
```xml
  <SerializeWrapPlayerOverrides>
    <Player>
      <Name>zymeth</Name>
      <SteamId>0</SteamId>
      <PersonalMaxMs>10</PersonalMaxMs>
      <OverrideEnabled>true</OverrideEnabled>
    </Player>
  </SerializeWrapPlayerOverrides>
```
but when executing `!pblimiter status` in-game it was still showing the default per player limit 0.5

Also found this in the logs:
```
09:30:32.9486 [WARN]   HaE_PBLimiter.PBPlayerTracker: Players name zymeth did not resolve to a steam ID!
```

I'm 100% sure the player name is correct because it works with all other Torch commands I use. I tried other player names known to the server and the result was the same.

Full config:
```xml
<?xml version="1.0" encoding="utf-8"?>
<ProfilerConfig xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <SerializeWrapTicks>20</SerializeWrapTicks>
  <SerializeWrapViolationsMult>0.1</SerializeWrapViolationsMult>
  <SerializeWrapTime>0.5</SerializeWrapTime>
  <SerializeWrapTimeOutTime>300</SerializeWrapTimeOutTime>
  <SerializeWrapSignificance>0.005</SerializeWrapSignificance>
  <SerializeWrapPerPlayer>true</SerializeWrapPerPlayer>
  <SerializeWrapAllowCleanup>true</SerializeWrapAllowCleanup>
  <SerializeWrapPlayerOverrides>
    <Player>
      <Name>zymeth</Name>
      <SteamId>0</SteamId>
      <PersonalMaxMs>10</PersonalMaxMs>
      <OverrideEnabled>true</OverrideEnabled>
    </Player>
  </SerializeWrapPlayerOverrides>
  <TakeIngameMeasurement>true</TakeIngameMeasurement>
</ProfilerConfig>
```

**Comment by azazar** [comment]
`!pblimiter status` doesn't show overridden limits. It's a bug. But that doesn't indicate that overridden limit doesn't work.

**Comment by sirhamsteralot** [comment]
@azazar actually i fixed this in commit 9ce37737ea366bfee1c7e68e9e0c1e580e7b8f7e

**Comment by sirhamsteralot** [comment]
the code for this is in https://github.com/sirhamsteralot/HaE-PBLimiter/blob/master/HaE%20PBLimiter/PBPlayerTracker.cs#L34-L43

I have only seen this fail if the game does not know of the player or if it is incorrect but i guess i should push a version that would show the short dump of the exception aswell?

**Comment by sirhamsteralot** [comment]
closed due to inactivity, please reopen it if there is any new information
