### ISSUE TITLE
Request: Player command to see used/available MS in 'Per Player'

### ISSUE THREAD

**Issue by dosfox** [sirhamsteralot/HaE-PBLimiter#33]
When enabling 'Per Player' limits, it would be helpful if a player could check to see how much of their limit they are utilizing.

**Comment by sirhamsteralot** [comment]
Good idea, going to check what is already there and implement if neccesary when getting back into modding

**Comment by sirhamsteralot** [comment]
Looks like i already implemented it, you can see it by using the !statistics command with individual limits enabled
