### ISSUE TITLE
Bug: !pblimiter status seems to output incorrect maximum

### ISSUE THREAD

**Issue by LordTylus** [sirhamsteralot/HaE-PBLimiter#34]
Hello there,

today I was notified that one player got incorrect max PB Limit shown in !pblimiter status window.

I am positive this was fixed before so I am confused on why it returned, or what I do wrong.

I verified it myself:

We have a per player limit which is 0.3
certain people defined by steamid have a limit of 1.0

https://cdn.discordapp.com/attachments/360599679714590743/775769009441472512/unknown.png

the limit works, but the display seems to be incorrect for unknown reasons.

**Comment by sirhamsteralot** [comment]
I will have a look into this on the upcoming update i intend to do when getting back into it

**Comment by sirhamsteralot** [comment]
Hello, i do not see of any way for this to occur, the only way i can see this happening if by chance the override for the player in question was not enabled. Please let me know if this happens again/reopen the issue if this occurs again, i will be closing the issue for now to keep it fresh ;)
