### ISSUE TITLE
Add option to exclude factions

### ISSUE THREAD

**Issue by fank** [sirhamsteralot/HaE-PBLimiter#4]
I added the new eem debug mod, and the problem here is that the PB should not be limited, because if they are stopped or removed (because of damage) it will break the whole gameplay.

So i need an option to exclude them by name, tag or exclude npc factions.
This is an important issue!

Just a quick overview:
![image](https://user-images.githubusercontent.com/1900106/45329031-b9967a00-b55e-11e8-821c-91c3294ddb5a.png)

**Comment by sirhamsteralot** [comment]
im actually working on this already, im adding an option to allow people to override the max runtime for certain playernames, so you could for example just tell it that "Civillian" has a max runtime of 10ms or something.

**Comment by fank** [comment]
I need an option to disable/skip, not to override. Because eem stuff never be touched by someone elsr

**Comment by sirhamsteralot** [comment]
you can use the override i added in version  v1.0.3.11 to give the NPC an overridden limit so the script doesnt interfere, just use the name displayed in the right collumn there to set the override and it should work.
