### ISSUE TITLE
Server crash with potential deadlock at `SuffixProfilePb`

### ISSUE THREAD

**Issue by ryo0ka** [sirhamsteralot/HaE-PBLimiter#45]
Crash log: [Torch-2024-10-30.log](https://github.com/user-attachments/files/17574844/Torch-2024-10-30.log) at line 13617

Server keeps crashing on reboot as the function is called. Not identified the specific block causing the issue, but removing the plugin from the server fixed the crash, with sim at 1.0. Somehow Torch app is saying "Not responding" every 10-sh seconds.

**Comment by sirhamsteralot** [comment]
Fixed in release v1.1.2.2. Please reopen if the issue occurs again
